version: "3.9"

services:
  web:
    build: .
    command: bash -c "
      uvicorn core.main:app
      --host 0.0.0.0 --port 80
      --reload
      "
    restart: always
    volumes:
      - ./:/backend
    ports:
      - '80:80'
    env_file:
      - .env
    depends_on:
      - db
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    command:
      mongod --quiet --logpath /dev/null

  db:
    image: postgres:14
    container_name: "db"
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./database/Init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"